# -*- coding: utf-8 -*-
inventor_error_vinculoeinstit = u'Não pode ter vínculo IFG e instituição de origem ao mesmo tempo'
inventor_error_semvinculoneminstit = u'Tem que ter algum vínculo IFG ou uma instiutição de origem'
arquivo_formato_naosuportado = u'Formato de arquivo não suportado'
telefone_error = u'Telefone desconhecido'
data_de_conclusao_error = u'O campo só pode ser preenchido quando o status da tarefa for alterado para "finalizada"'
data_de_conclusao_error2 = u'O campo deve ser preenchido quando o status da tarefa for "Finalizada"'
tarefa_anexo_error = u'Documento(s) comprobatório(s) da execução da tarefa que deve(m) ser carregado(s) no sistema antes da alteração do status para "Finalizada"'
tarefa_realizacao_inicio_erro = u'Deve preencher a data de início'
tarefa_realizacao_final_erro = u'Deve preencher a data de finalização'
tarefa_cadastro_erro = u'A data de cadastro não pode ser superior à data de finalização'
cocriador_already_criador_erro = u'O Co-criador já está configurado como Criador'