# -*- coding: utf-8 -*-
observacao = u'Campo aberto para redigir qualquer tipo de observação, como algo dito pela Comissão ou alguma fala do inventor.'
anexo_tarefa = u'Toda petição possui um documento comprobatório do cumprimento da mesma; este deve ser carregado (uploaded) no sistema antes da data limite da realização dessa atividade.'
doc_comprobatorio = u'Documento comprobatório da existência do vínculo entre o Inventor e o IFG'
docs_pessoais = u'Documentos pessoais (RG e CPF) juntos no mesmo arquivo'
contrato_formulario = u'Formulário de Requerimento de Averbação e Registro'
contrato_carta_explicativa = u'Pode ser usada tanto para formalizar o pedido quanto para apresentação de informações relevantes a respeito do contrato e da fatura e para apresentação esclarecimentos ou justificativas necessárias ao exame dos requerimentos e petições.'
contrato_gru = u'Guia de Recolhimento da União'
contrato_fatura = u'Para compor o processo, o requerente deverá apresentar uma cópia autenticada em cartório do documento (contrato e aditivo ou fatura).'
contrato_ficha_cadastro =u'Ficha cadastro	Arquivo	Ficha cadastral da empresa cessionária'
possiveis_licenciadores = u'Empresas que poderiam se interessar pela tecnologia em questão'
